pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: CmdLine@2
  inputs:
    script: 'dotnet tool install --global dotnet-coverage'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: Debug

- task: CmdLine@2
  inputs:
    script: 'dotnet-coverage collect "dotnet test ./TUnit.TestProject/TUnit.TestProject.csproj --configuration Debug --no-build --framework net8.0" -f xml -o "wiremock-coverage-tunit.xml"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/TUnit.TestProject.csproj'
    publishTestResults: false