pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: CmdLine@2
  inputs:
    script: 'dotnet tool install --global dotnet-coverage'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/TUnit.NugetTester.csproj'
    arguments: '--configuration Debug --framework net8.0'

- task: CmdLine@2
  inputs:
    script: 'dotnet-coverage collect "dotnet test ./tools/tunit-nuget-tester/TUnit.NugetTester/TUnit.NugetTester/TUnit.NugetTester.csproj --configuration Debug --no-build --framework net8.0 -p:TUnitVersion=0.1.812" -f xml -o "wiremock-coverage-tunit.xml"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/TUnit.NugetTester.csproj'
    publishTestResults: false